#
# Makefile for the linux ramfs routines.
#
obj-y += devfs.o devfs_journal.o devfs_security.o  bitmap.o devfs_slab.o devfs_pmfs_balloc.o devfs_inode.o devfs_pmfs_xip.o inode.o persist.o wprotect.o journal.o dir.o file.o bbuild.o symlink.o namei.o ioctl.o devfs_super.o devfs_scheduler.o devfs_scalability.o #devfs_balloc.o devfs_dir.o  devfs_mm.o devmem.o devfs_kerntest.o snappy.o
#devfs-y  += devfs_journal.o devfs_security.o
#devfs-y  += devfs_security.o
#pmfs-$(CONFIG_PMFS_WRITE_PROTECT) += wprotect.o
#pmfs-$(CONFIG_PMFS_XIP) += xip.o
